### ISSUE TITLE
不能读取1.8的存档。

### ISSUE THREAD

**Issue by ExerciseBook** [lipengg/MCImporter#4]
[log.txt](https://github.com/lipengg/MCImporter/files/371398/log.txt)

![20160719201240](https://cloud.githubusercontent.com/assets/6327311/16949398/2cb64424-4ded-11e6-954f-545d16e3597b.png)

存档下载：
[trees.zip](https://github.com/lipengg/MCImporter/files/371401/trees.zip)
# 滑稽

**Comment by LiXizhi** [comment]
![image](https://cloud.githubusercontent.com/assets/94537/20386474/c472a6dc-acf6-11e6-9fd2-184f443f7406.png)


working on mine

**Comment by ExerciseBook** [comment]
已检查，是dll的缺失。

**Comment by ExerciseBook** [comment]
已检查，是dll的缺失。
